sudo: false
language: elixir
elixir:
  - 1.0.5
otp_release:
  - 17.5
  - 18.0
script: mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix -h
  - MIX_ENV=docs mix inch.report
  - git branch -a
  
